General code cleanup, inc adding comments.

diff --git a/.github/workflows/acquia-backup-databases.yml b/.github/workflows/acquia-backup-databases.yml
--- a/.github/workflows/acquia-backup-databases.yml
+++ b/.github/workflows/acquia-backup-databases.yml
@@ -61,7 +61,7 @@ jobs:
         run: |
           # The first time we run api:environments:database-list acli very
           # kindly also outputs a string asking the user to share
-          # anonymous user data along with the JSON output causing error
+          # anonymous user data along with the JSON output causing an error
           # further down the chain - this simply mitigates that.
           acsf_request=$(php acli.phar api:environments:database-list \
             --filter='${{ inputs.filter }}' \
@@ -75,7 +75,8 @@ jobs:
             ${{ secrets.ENVIRONMENT_ID }} \
             | jq '.[] | .name')
 
-          # Processes the output of databases.
+          # Processes the output of databases to allow the data to
+          # be passed to the 'Backing up databases' step.
           delimiter="$(openssl rand -hex 8)"
           echo "db_list<<${delimiter}" >> "${GITHUB_OUTPUT}"
           echo ${database_list} >> ${GITHUB_OUTPUT}
@@ -85,14 +86,14 @@ jobs:
         run: |
 
           # Split db_list into an array.
-          IFS=', ' read -r -a db_array <<< "${{ steps.get_databases.outputs.db_list }}"
+          IFS=', ' read -r -a backup_array <<< "${{ steps.get_databases.outputs.db_list }}"
 
           # Loop through the array of databases and attempt to 
           # perform a backup for each database.
           i=0
-          while [ $i -lt ${#db_array[@]} ]
+          while [ $i -lt ${#backup_array[@]} ]
           do
-            php acli.phar api:environments:database-backup-create ${{ secrets.ENVIRONMENT_ID }} ${db_array[$i]}
-            echo "💧 Successfully backed up database "${db_array[$i]}"" || echo "❌ Error backing up database $db_list. See logs."
+            php acli.phar api:environments:database-backup-create ${{ secrets.ENVIRONMENT_ID }} ${backup_array[$i]}
+            echo "💧 Successfully backed up database "${backup_array[$i]}"" || echo "❌ Error backing up database "${backup_array[$i]}". See logs."
             i=$((i + 1))
           done
