Adding DB import debug output.

diff --git a/.github/workflows/acquia-backup-databases.yml b/.github/workflows/acquia-backup-databases.yml
--- a/.github/workflows/acquia-backup-databases.yml
+++ b/.github/workflows/acquia-backup-databases.yml
@@ -87,15 +87,6 @@ jobs:
           echo ${{ steps.get_databases.outputs.db-list }}
           echo "DB import end"
 
-          db_array=(${{ steps.get_databases.outputs.db-list }})
-          i=0
-          len=${#db_array[@]}
-          while [ $i -lt $len ];
-          do
-              echo ${db_array[$i]}
-              let i++
-          done
-
-          # while read database; do \
-          #   php acli.phar api:environments:database-backup-create ${{ secrets.ENVIRONMENT_ID }} $database && echo "💧 Successfully backed up database $database!" || echo "❌ Error backing up database $database. See logs."; exit 1 \
-          # done < (split ${{ steps.get_databases.outputs.db-list }} by space)
+          while read db_list; do \
+            php acli.phar api:environments:database-backup-create ${{ secrets.ENVIRONMENT_ID }} $db_list && echo "💧 Successfully backed up database $db_list!" || echo "❌ Error backing up database $db_list. See logs."; exit 1 \
+          done < (split ${{ steps.get_databases.outputs.db-list }} by space)
