Perform the do-while command on one line.

diff --git a/.github/workflows/acquia-backup-databases.yml b/.github/workflows/acquia-backup-databases.yml
--- a/.github/workflows/acquia-backup-databases.yml
+++ b/.github/workflows/acquia-backup-databases.yml
@@ -66,7 +66,5 @@ jobs:
       - name: Backing up databases
         run: |
           while read database; do \
-            php acli.phar api:environments:database-backup-create ${{ secrets.ENVIRONMENT_ID }} $database \
-              && echo "💧 Successfully backed up database $database!" \
-              || echo "❌ Error backing up database $database. See logs."; exit 1 \
+            php acli.phar api:environments:database-backup-create ${{ secrets.ENVIRONMENT_ID }} $database && echo "💧 Successfully backed up database $database!" || echo "❌ Error backing up database $database. See logs."; exit 1 \
           done <${{ steps.get_databases.outputs.databases }}
