Adding DB import debug output.

diff --git a/.github/workflows/acquia-backup-databases.yml b/.github/workflows/acquia-backup-databases.yml
--- a/.github/workflows/acquia-backup-databases.yml
+++ b/.github/workflows/acquia-backup-databases.yml
@@ -87,6 +87,13 @@ jobs:
           echo ${{ steps.get_databases.outputs.db-list }}
           echo "DB import end"
 
-          while read db_list; do \
-            php acli.phar api:environments:database-backup-create ${{ secrets.ENVIRONMENT_ID }} $db_list && echo "💧 Successfully backed up database $db_list!" || echo "❌ Error backing up database $db_list. See logs."; exit 1 \
-          done <${{ steps.get_databases.outputs.db-list }}
+
+          IFS=', ' read -r -a array <<< "${{ steps.get_databases.outputs.db-list }}"
+          echo "Item 1"
+          echo "${array[0]}"
+          echo "Item 2"
+          echo "${array[1]}"
+
+          # while read db_list; do \
+          #   php acli.phar api:environments:database-backup-create ${{ secrets.ENVIRONMENT_ID }} $db_list && echo "💧 Successfully backed up database $db_list!" || echo "❌ Error backing up database $db_list. See logs."; exit 1 \
+          # done <${{ steps.get_databases.outputs.db-list }}
