Cleanup of 'Backing up databases' step.

diff --git a/.github/workflows/acquia-backup-databases.yml b/.github/workflows/acquia-backup-databases.yml
--- a/.github/workflows/acquia-backup-databases.yml
+++ b/.github/workflows/acquia-backup-databases.yml
@@ -91,9 +91,8 @@ jobs:
           i=0
           while [ $i -lt ${#db_array[@]} ]
           do
-            # php acli.phar api:environments:database-backup-create ${{ secrets.ENVIRONMENT_ID }} ${array[$i]} && echo "💧 Successfully backed up database ${array[$i]}!" || echo "❌ Error backing up database ${array[$i]}. See logs."; exit 1 \
+            php acli.phar api:environments:database-backup-create ${{ secrets.ENVIRONMENT_ID }} ${db_array[$i]} && echo "💧 Successfully backed up database ${db_array[$i]}" || echo "❌ Error backing up database ${db_array[$i]}. See logs."; exit 1 \
             echo "${db_array[$i]}"
-            echo "."
             i=$((i + 1))
           done
 
